### ISSUE TITLE
https://www.python.org/dev/peps/pep-0440/

### ISSUE THREAD

**Issue by xpunkt** [whyscream/dspam-milter#30]
i get PEP 440 problem with current dspam-milter

in case some like to help me solve gentoo ebuild my work is here

layman -a fidonet
emerge --autounmask-write dspam-milter
emerge --buildpkgonly dspam-milter

**Comment by tomhendrikx** [comment]
What is the actual problem? I don't use ebuilds, but if you need a tarball to base your package on, you should use a released one, as that has an actual semver compantible version. Latest release at https://github.com/whyscream/dspam-milter/releases should work i think.

Otherwise, please state your actual problem ;)

**Comment by xpunkt** [comment]
its not ebuilds, imho you miss to build test more for that i started with in this thread here, PEP 440 is not gentoo specific in ebuilds

great to see dspam still lives in good fame

**Comment by whyscream** [comment]
As long as you cannot explain your problem, I cannot help you. When you talk about ebuilds, it seems to me that I need to run your ebuild in order to find out your actual issue: I'm sorry but I can't do that. 

All releases have proper x.y.z versions, as described in the PEP you talk about. So I don't understand your problem.

**Comment by xpunkt** [comment]
pep 440 are not very gentoo or even ebuild specific, i will make a web error log when i have time to debug my own fails later

i could use precompiled problems to hide precompiled problems reports

would it be possible to make dspam in 100% python aswell ?

i ask for this since it would solve more problems i have not yet reported :(

**Comment by whyscream** [comment]
Closing until you have time to debug and create a log.
