### ISSUE TITLE
Lack of Improbability header

### ISSUE THREAD

**Issue by falon** [whyscream/dspam-milter#36]
Compared to available DSPAM headers, the current implementation of dspam-milter (0.3.4.post0) doesn't offer the "Improbability" header. Such as:
`X-DSPAM-Improbability: 1 in 9809 chance of being spam`

**Comment by whyscream** [comment]
The improbability header contains some kind of calculation done based on statistics from the complete message database. Currently the statistics database is not available through the DSPAM daemon: it has access for it's own purposes, but it does not have any means for clients connecting to it to query the database directly, or retrieve any pre-cooked statistics. I decided against accessing the DSPAM database from the milter to keep the design simple.

When you setup DSPAM using `stdout` mode, and enable the `ImprobabilityDrive` in dspam itself (and try adding the field to the milter's `headers` setting), the header should be present since it's added to the message body by dspam itself. In all other modes, the header cannot be present, unfortunately.

If you don't get the header when using the `stdout` mode, please show the logging of a single message handled by dspam-milter in debug mode so I can investigate further.

**Comment by falon** [comment]
Thank you for the clarification.
I didn't notice of this hardcoded conf:
`client_args='--process --deliver=summary'`

Previously I run dspam daemon in standard LMTP mode with
`--deliver=innocent,spam -d %u`
and as you say in this way I read the Improbability header.

If the dspam-milter default DLMTP deliver is better in this way because it does less query to database, then I'll keep this conf without Improbability header.
